# -*- coding: utf-8 -*-
"""Agno_reference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QqxtmDprU_svdCXmbr8EcmzMu99Z0in9
"""



"""#Agno Parameters Explained

Agno's functions have a lot of parameters. You can customize the agent only by modifying some of them to true or false or giving them the relevant parameters.

## The Agent function
Here are all of the parameters for the Agent Function, and a brief decription of what exactly they do.

# Agno Agent Parameters Reference

## Core Configuration
| Parameter | Description |
|-----------|-------------|
| `model` | Model to use (Model object or string like `provider:model_id`) |
| `name` | Agent name |
| `id` | Agent ID (autogenerated UUID if not set) |
| `introduction` | Introduction message for the Agent |

## Session & User
| Parameter | Description |
|-----------|-------------|
| `user_id` | Default user_id for this agent |
| `session_id` | Default session_id (autogenerated if not set) |
| `session_state` | Default session state (persisted in database across runs) |
| `add_session_state_to_context` | Add session_state to context |
| `overwrite_db_session_state` | Overwrite DB session state with provided state |
| `enable_agentic_state` | Give agent tools to update session_state dynamically |
| `cache_session` | Cache session in memory for faster access |
| `search_session_history` | Allow searching through previous sessions |
| `num_history_sessions` | Number of past sessions to include in search (keep to 2-3) |

## Dependencies
| Parameter | Description |
|-----------|-------------|
| `dependencies` | Dependencies available for tools and prompt functions |
| `add_dependencies_to_context` | Add dependencies to user prompt |

## Database & Memory
| Parameter | Description |
|-----------|-------------|
| `db` | Database to use for this agent |
| `memory_manager` | Memory manager to use |
| `enable_agentic_memory` | Enable agent to manage user memories |
| `enable_user_memories` | Create/update user memories at end of runs |
| `add_memories_to_context` | Add user memories reference to response |
| `enable_session_summaries` | Create/update session summaries at end of runs |
| `add_session_summary_to_context` | Add session summaries to context |
| `session_summary_manager` | Session summary manager |

## History
| Parameter | Description |
|-----------|-------------|
| `add_history_to_context` | Add chat history to messages sent to Model |
| `num_history_runs` | Number of historical runs to include |
| `num_history_messages` | Number of historical messages to include |
| `max_tool_calls_from_history` | Max tool calls from history to keep in context |
| `store_media` | Store media in database |
| `store_tool_messages` | Store tool results in database |
| `store_history_messages` | Store history messages in database |

## Knowledge
| Parameter | Description |
|-----------|-------------|
| `knowledge` | Agent Knowledge base |
| `knowledge_filters` | Filters to apply to knowledge base |
| `enable_agentic_knowledge_filters` | Let agent choose knowledge filters |
| `add_knowledge_to_context` | Enable RAG by adding knowledge references to prompt |
| `knowledge_retriever` | Custom function to get references |
| `references_format` | Format of references (`json` or `yaml`) |

## Tools
| Parameter | Description |
|-----------|-------------|
| `tools` | List of tools provided to the Model |
| `tool_call_limit` | Max tool calls allowed per run |
| `tool_choice` | Controls which tool is called |
| `tool_hooks` | Functions that run between tool calls |
| `pre_hooks` | Functions/guardrails called before processing |
| `post_hooks` | Functions/guardrails called after output generation |

## Reasoning
| Parameter | Description |
|-----------|-------------|
| `reasoning` | Enable step-by-step reasoning |
| `reasoning_model` | Model to use for reasoning |
| `reasoning_agent` | Agent to use for reasoning |
| `reasoning_min_steps` | Minimum reasoning steps (default: 1) |
| `reasoning_max_steps` | Maximum reasoning steps (default: 10) |

## Default Tools
| Parameter | Description |
|-----------|-------------|
| `read_chat_history` | Add tool to read chat history |
| `search_knowledge` | Add tool to search knowledge base (default: True) |
| `update_knowledge` | Add tool to update knowledge base |
| `read_tool_call_history` | Add tool to get tool call history |
| `send_media_to_model` | Send media to LLM (if False, only available to tools) |

## System Message & Instructions
| Parameter | Description |
|-----------|-------------|
| `system_message` | System message as string, function, or Message |
| `system_message_role` | Role for system message (default: "system") |
| `build_context` | Build context (set False to skip) |
| `description` | Agent description added to system message start |
| `instructions` | Instructions for the agent |
| `expected_output` | Expected output from the Agent |
| `additional_context` | Additional context at end of system message |
| `markdown` | Format output using markdown |
| `add_name_to_context` | Add agent name to instructions |
| `add_datetime_to_context` | Add current datetime to instructions |
| `add_location_to_context` | Add current location to instructions |
| `timezone_identifier` | Custom timezone for datetime |
| `resolve_in_context` | Resolve variables in context |
| `additional_input` | Additional input messages |
| `user_message_role` | Role for user message (default: "user") |
| `build_user_context` | Build user context |

## Retries & Parsing
| Parameter | Description |
|-----------|-------------|
| `retries` | Number of retries (default: 0) |
| `delay_between_retries` | Delay between retries in seconds |
| `exponential_backoff` | Use exponential backoff for retries |
| `parser_model` | Model for parsing responses |
| `parser_model_prompt` | Prompt for parser model |
| `input_schema` | Input schema (Pydantic BaseModel) |
| `output_schema` | Output schema (Pydantic BaseModel) |
| `parse_response` | Parse response (default: True) |
| `output_model` | Model for output generation |
| `output_model_prompt` | Prompt for output model |
| `structured_outputs` | Enable structured outputs |
| `use_json_mode` | Use JSON mode instead of structured outputs |
| `save_response_to_file` | Save response to file path |

## Streaming & Events
| Parameter | Description |
|-----------|-------------|
| `stream` | Enable streaming |
| `stream_events` | Stream intermediate steps |
| `stream_intermediate_steps` | Stream intermediate steps |
| `store_events` | Store events |
| `events_to_skip` | List of RunEvents to skip |

## Culture & Metadata
| Parameter | Description |
|-----------|-------------|
| `role` | Agent role |
| `metadata` | Metadata stored with this agent |
| `culture_manager` | Culture manager |
| `enable_agentic_culture` | Enable agentic culture |
| `update_cultural_knowledge` | Update cultural knowledge |
| `add_culture_to_context` | Add culture to context |

## Debug & Telemetry
| Parameter | Description |
|-----------|-------------|
| `debug_mode` | Enable debug mode |
| `debug_level` | Debug level (1 or 2) |
| `telemetry` | Log minimal telemetry (default: True) |

--------------------------------------------------------------------------------

# Agno Workflow Parameters Reference

## Core Configuration
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `name` | `Optional[str]` | `None` | Workflow name |
| `id` | `Optional[str]` | `None` | Workflow ID (autogenerated if not set) |
| `description` | `Optional[str]` | `None` | Workflow description |
| `steps` | `Optional[WorkflowSteps]` | `None` | Workflow steps - can be a callable function, Steps object, or list of steps |

## Session & User
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `session_id` | `Optional[str]` | `None` | Default session_id (autogenerated if not set) |
| `user_id` | `Optional[str]` | `None` | Default user_id for this workflow |
| `session_state` | `Optional[Dict[str, Any]]` | `None` | Default session state (stored in database to persist across runs) |
| `cache_session` | `bool` | `False` | Cache the current workflow session in memory for faster access |

## Database
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `db` | `Optional[BaseDb]` | `None` | Database to use for this workflow |

## Streaming & Events
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `stream` | `Optional[bool]` | `None` | Stream the response from the Workflow |
| `stream_events` | `bool` | `False` | Stream the intermediate steps from the Workflow |
| `stream_executor_events` | `bool` | `True` | Stream events emitted by the Step executor (agent/team events) together with Workflow events |
| `store_events` | `bool` | `False` | Persist the events on the run response |
| `events_to_skip` | `Optional[List[...]]` | `None` | Events to skip when persisting the events on the run response |
| `store_executor_outputs` | `bool` | `True` | Control whether to store executor responses (agent/team responses) in flattened runs |

## History
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `add_workflow_history_to_steps` | `bool` | `False` | Add the workflow history to the steps |
| `num_history_runs` | `int` | `None` | Number of runs to include in workflow history (all if not provided) |

## Input/Output
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `input_schema` | `Optional[Type[BaseModel]]` | `None` | Input schema to validate the input to the workflow |
| `metadata` | `Optional[Dict[str, Any]]` | `None` | Metadata stored with this workflow |

## WebSocket
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `websocket_handler` | `Optional[WebSocketHandler]` | `None` | WebSocket handler for real-time communication |

## Debug & Telemetry
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `debug_mode` | `Optional[bool]` | `False` | If True, the workflow runs in debug mode |
| `telemetry` | `bool` | `True` | Log minimal telemetry for analytics |

---

# Workflow Methods

## `run()`
Execute the workflow synchronously with optional streaming.

**Parameters:**
- `input`: The input to send to the workflow
- `additional_data`: Additional data to include with the input
- `user_id`, `session_id`, `session_state`: Session configuration
- `audio`, `images`, `videos`, `files`: Media files to include
- `stream`: Whether to stream the response
- `stream_events`: Whether to stream intermediate steps

**Returns:** `WorkflowRunOutput` or `Iterator[WorkflowRunOutputEvent]`

## `arun()`
Execute the workflow asynchronously with optional streaming.

## `print_response()`
Print workflow execution with rich formatting and optional streaming.

## `cli_app()`
Run an interactive command-line interface to interact with the workflow.

## `cancel_run(run_id: str)`
Cancel a running workflow execution.

## `get_session(session_id)`
Get the session for the given session ID.

## `get_session_state(session_id)`
Get the session state for the given session ID.

## `delete_session(session_id)`
Delete a session.

# Agno Toolkits Reference

Agno provides 120+ pre-built toolkits. Here's a comprehensive reference organized by category.

---

## Search Toolkits

### DuckDuckGo
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `enable_search` | `bool` | `True` | Enable DuckDuckGo search function |
| `enable_news` | `bool` | `True` | Enable DuckDuckGo news function |
| `modifier` | `Optional[str]` | `None` | Modifier for search request |
| `fixed_max_results` | `Optional[int]` | `None` | Fixed number of maximum results |
| `proxy` | `Optional[str]` | `None` | Proxy for search request |
| `timeout` | `Optional[int]` | `10` | Max seconds to wait for response |
| `verify_ssl` | `bool` | `True` | Verify SSL certificates |

**Functions:** `duckduckgo_search`, `duckduckgo_news`

---

### Tavily
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `api_key` | `Optional[str]` | `None` | Tavily API key (uses env var if not set) |
| `enable_search` | `bool` | `True` | Enable search functionality |
| `enable_search_context` | `bool` | `False` | Enable search context API |
| `max_tokens` | `int` | `6000` | Max tokens in search results |
| `include_answer` | `bool` | `True` | Include AI-generated answer summary |
| `search_depth` | `Literal['basic', 'advanced']` | `'advanced'` | Search depth |
| `format` | `Literal['json', 'markdown']` | `'markdown'` | Output format |

**Functions:** `web_search_using_tavily`, `web_search_with_tavily`

---

### Exa
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `enable_search` | `bool` | `True` | Enable search functionality |
| `enable_get_contents` | `bool` | `True` | Enable content retrieval |
| `enable_find_similar` | `bool` | `True` | Enable finding similar content |
| `enable_answer` | `bool` | `True` | Enable AI-powered answers |
| `text_length_limit` | `int` | `1000` | Max text content per result |
| `num_results` | `Optional[int]` | `None` | Default number of results |
| `livecrawl` | `str` | `"always"` | Livecrawl behavior |
| `include_domains` | `Optional[List[str]]` | `None` | Restrict to these domains |
| `exclude_domains` | `Optional[List[str]]` | `None` | Exclude these domains |
| `category` | `Optional[str]` | `None` | Category filter (news, research paper, etc.) |

**Functions:** `search_exa`, `get_contents`, `find_similar`, `exa_answer`

---

### Brave Search
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `api_key` | `Optional[str]` | `None` | Brave API key |
| `fixed_max_results` | `Optional[int]` | `None` | Fixed number of max results |
| `fixed_language` | `Optional[str]` | `None` | Fixed language for results |
| `enable_brave_search` | `bool` | `True` | Enable brave_search function |

**Functions:** `brave_search`

---

### SerperApi
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `api_key` | `str` | - | API key for authentication |
| `location` | `str` | `"us"` | Location to search from |
| `enable_search` | `bool` | `True` | Enable search functionality |
| `enable_search_news` | `bool` | `True` | Enable news search |
| `enable_search_scholar` | `bool` | `True` | Enable scholar search |
| `enable_scrape_webpage` | `bool` | `True` | Enable webpage scraping |

**Functions:** `search_google`, `search_news`, `search_scholar`, `scrape_webpage`

---

### Linkup
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `api_key` | `Optional[str]` | `None` | Linkup API key |
| `depth` | `Literal` | `"standard"` | Search depth: "standard" or "deep" |
| `output_type` | `Literal` | `"searchResults"` | Output format |
| `enable_web_search_with_linkup` | `bool` | `True` | Enable web search |

**Functions:** `web_search_with_linkup`

---

### Valyu (Academic Search)
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `api_key` | `Optional[str]` | `None` | Valyu API key |
| `enable_academic_search` | `bool` | `True` | Enable academic search |
| `enable_web_search` | `bool` | `True` | Enable web search |
| `enable_paper_search` | `bool` | `True` | Enable paper search |
| `text_length` | `int` | `1000` | Max text content per result |
| `max_results` | `int` | `10` | Max results to return |
| `relevance_threshold` | `float` | `0.5` | Min relevance score |

**Functions:** `academic_search`, `web_search`, `paper_search`

---

## Finance Toolkits

### YFinance
All functions enabled by default - no configuration parameters needed.

**Functions:**
| Function | Description |
|----------|-------------|
| `get_current_stock_price` | Get current stock price |
| `get_company_info` | Get detailed company information |
| `get_historical_stock_prices` | Get historical stock prices |
| `get_stock_fundamentals` | Get fundamental stock data |
| `get_income_statements` | Get company income statements |
| `get_key_financial_ratios` | Get key financial ratios |
| `get_analyst_recommendations` | Get analyst recommendations |
| `get_company_news` | Get latest company news |
| `get_technical_indicators` | Get technical indicators |

---

### OpenBB
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `obb` | `Any` | `None` | OpenBB app instance |
| `openbb_pat` | `str` | `None` | Personal Access Token |
| `provider` | `str` | `"yfinance"` | Data provider |
| `enable_get_stock_price` | `bool` | `True` | Enable stock price retrieval |
| `enable_search_company_symbol` | `bool` | `False` | Enable symbol search |
| `enable_get_company_news` | `bool` | `False` | Enable company news |
| `enable_get_company_profile` | `bool` | `False` | Enable company profile |
| `enable_get_price_targets` | `bool` | `False` | Enable price targets |

**Functions:** `get_stock_price`, `search_company_symbol`, `get_price_targets`, `get_company_news`, `get_company_profile`

---

## Reasoning Toolkits

### ReasoningTools
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `think` | `bool` | `True` | Enable think tool |
| `analyze` | `bool` | `True` | Enable analyze tool |
| `add_instructions` | `bool` | `False` | Add default instructions |
| `add_few_shot` | `bool` | `False` | Add few-shot examples |

**Functions:** `think`, `analyze`

---

### KnowledgeTools
| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `knowledge` | `Knowledge` | Required | Knowledge base to search |
| `think` | `bool` | `True` | Enable think tool |
| `search` | `bool` | `True` | Enable search tool |
| `analyze` | `bool` | `True` | Enable analyze tool |
| `add_instructions` | `bool` | `True` | Add default instructions |
| `add_few_shot` | `bool` | `True` | Add few-shot examples |

**Functions:** `think`, `search`, `analyze`

---

## All Available Toolkit Categories

### Search
- Arxiv, BaiduSearch, DuckDuckGo, Exa, HackerNews, Pubmed, SearxNG, SerperApi, Serpapi, Tavily, Linkup, Valyu, Wikipedia

### Social
- Discord, Email, Gmail, Slack, Telegram, Twilio, WhatsApp, Webex, X (Twitter), Reddit, Zoom

### Web Scraping
- AgentQL, BrowserBase, Crawl4AI, Jina Reader, Newspaper, Newspaper4k, Website, Firecrawl, Spider, Trafilatura, BrightData

### Data/Database
- CSV, DuckDb, Pandas, Postgres, Redshift, SQL, Google BigQuery, Neo4j, Zep, MCP Toolbox

### Local
- Calculator, Docker, File, Python, Shell, Local File System, Sleep

### Native Model Toolkits
- Azure OpenAI, Groq, Morph, Nebius

### Others
- Airflow, Apify, AWS Lambda, AWS SES, CalCom, Cartesia, Composio, Confluence, Custom API, DALL-E, Eleven Labs, E2B, Fal, Financial Datasets, Giphy, GitHub, Google Maps, Google Calendar, Google Sheets, Jira, Linear, Lumalabs, MLX Transcribe, ModelsLabs, Notion, Nano Banana, OpenBB, Openweather, Replicate, Resend, Todoist, YFinance, YouTube, Bitbucket, Brandfetch, ClickUp, Desi Vocal, EVM, Knowledge, Mem0, Memori, OpenCV, Reasoning, Spotify, User Control Flow, Visualization, WebTools, Zendesk

---

## Common Toolkit Parameters

All toolkits support these base parameters:

| Parameter | Type | Default | Description |
|-----------|------|---------|-------------|
| `name` | `str` | - | Toolkit name |
| `tools` | `List[Callable]` | - | List of tool functions |
| `instructions` | `str` | - | Instructions for using the toolkit |
| `add_instructions` | `bool` | `False` | Add instructions to agent context |
| `include_tools` | `list[str]` | `None` | Only include these tools |
| `exclude_tools` | `list[str]` | `None` | Exclude these tools |
| `cache_results` | `bool` | `False` | Enable result caching |
| `cache_ttl` | `int` | `3600` | Cache TTL in seconds |

---

## Usage Example

```python
from agno.agent import Agent
from agno.tools.duckduckgo import DuckDuckGoTools
from agno.tools.yfinance import YFinanceTools

agent = Agent(
    tools=[
        DuckDuckGoTools(cache_results=True),
        YFinanceTools()
    ],
)

agent.print_response("What's the latest news on AAPL stock?", markdown=True)
"""